services:
  tailscale-home:
    image: tailscale/tailscale:latest
    privileged: yes
    container_name: tailscale-home
    hostname: tailscale-home
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${TAILSCALEHOME_PATH}/ts-home/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000 # Expose Portainer on host for local management
    volumes:
      - portainer_data:/data
    restart: unless-stopped

  nginx-tailscale-home:
    image: nginx:latest
    container_name: nginx-tailscale-home
    network_mode: service:tailscale-home
    volumes:
      - ${NGINX_PATH}/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  portainer_data:
